### ISSUE TITLE
Storing token in environment rather than global options

### ISSUE THREAD

**Issue by soodoku** [rOpenGov/rtimes#12]
Dear Scott,

A minor suggestion. @hadley recommends storing tokens in environment rather than options. It makes sense to me. Options are global afaik. And we probably want something like env. 

https://cran.r-project.org/web/packages/httr/vignettes/api-packages.html

Hope you are well.

Gaurav

**Comment by sckott** [comment]
yeah, can change, I do use env vars for keys for travis testing - just not for users, but will change
