### ISSUE TITLE
Faceting in article search does not seem to work

### ISSUE THREAD

**Issue by andybega** [rOpenGov/rtimes#20]
Hello, I tried the examples from the `as_search` examples and they all seem to give the same results, without facets:

```
library("rtimes")

# add example without facets
x1 <- as_search(q="bailout", begin_date = "20081001", end_date = '20081201')
Sys.sleep(1)
# faceting
x2 <- as_search(q="bailout", facet_field = 'section_name', begin_date = "20081001",
   end_date = '20081201')
Sys.sleep(1)
## with facet filtering
x3 <- as_search(q="bailout", facet_field = 'section_name', begin_date = "20081001",
   end_date = '20081201', facet_filter = TRUE)
```

The `facets` item is `NULL` in all 3 of the results lists for me. 

```
> x1$facets
NULL
> x2$facets
NULL
> x3$facets
NULL
```

**Comment by sckott** [comment]
yeah, another place where their API is misbehaving, docs show facets http://developer.nytimes.com/article_search_v2.json#/README but if you curl the request there are no facets to be found:

```
curl 'http://api.nytimes.com/svc/search/v2/articlesearch.json?q=bailout&page=0&begin_date=20081001&end_date=20081005&facet_field=section_name&api-key=<yourkey>' | jq '.response | keys'
```

i have never got a response from their developers so we'll see if they respond, not likely

**Comment by sckott** [comment]
an open issue https://github.com/NYTimes/public_api_specs/issues/34 so presumably they know about it

**Comment by andybega** [comment]
Thanks for looking into it. Nothing to be done then until the API issue is resolved...

**Comment by sckott** [comment]
https://github.com/NYTimes/public_api_specs/issues/34#issuecomment-337004610
