### ISSUE TITLE
Differing fields?

### ISSUE THREAD

**Issue by elinw** [rOpenGov/rtimes#22]
I've been doing a page at a time for article search (so 10 articles each). But I'm getting back a different number of columns in each batch. Sometimes there are 26 columns, sometimes 24 or 26.  Is that normal?

**Comment by sckott** [comment]
not sure, saw the PR, will have a look

**Comment by sckott** [comment]
We're binding lists from parsing json into data.frames and so results may vary in what fields are given back - so I think its okay as is - `dplyr::bind_rows` can handle binding together data.frame's with different numbers of columns

**Comment by elinw** [comment]
Yes this is what I came up with as well, I notices that it differed for different time periods so that is part of it, and bind_rows() handles it fine.
