### ISSUE TITLE
Suggestion for vignette

### ISSUE THREAD

**Issue by soodoku** [rOpenGov/rtimes#9]
Scott -

I used rtimes to chart coverage of civil rights issues in NYT. I believe it will make a reasonable example for the vignette.

Here's more:
https://github.com/soodoku/nyt-civil-rights

**Comment by sckott** [comment]
:rocket: awesome. Thanks for sharing. I will put it in the vignette or a separate one maybe

p.s. if you have any feedback on making the pkg better... :)

**Comment by sckott** [comment]
@soodoku I put a vignette in using your code, modified of course. 

https://github.com/rOpenGov/rtimes/blob/master/vignettes/nyt_civil_rights.Rmd

Does that look okay?  I only did it with one query phrase, instead of all of them, but for all dates.

**Comment by soodoku** [comment]
Sure. Looks good to me. By the way, sent you an email re. rnoaa

**Comment by sckott** [comment]
Great. 

Yes, I replied to that email
